### ISSUE TITLE
User can view an NFT

### ISSUE THREAD

**Issue by anthony-urbina** [AnthonyUrbina/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can view an NFT

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will load the page and be able to view an NFT of the bat.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-09-26 at 11 24 32 AM](https://user-images.githubusercontent.com/109625982/192352126-40c9e679-4659-440d-ab25-f6ea9543fedb.png)

![Screen Shot 2022-09-26 at 11 26 23 AM](https://user-images.githubusercontent.com/109625982/192352458-c5d8656b-c64a-43ea-b433-894ea44355d9.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a div[data-view="swipe-page"] to the HTML
- [x]  Add a header[data-view="swipe-page"] to the HTML
- [x] Set up a card for the nft image and title in the HTML
- [x]  Create a helper function that generates a random integer
- [x] Send a network request to the eth api to retrieve an nft image and title
  - [x]  Only retrieve the nft image and title at the index specified in the return value of the random number helper function
  - [x]  Console.log to ensure you are receiving the correct data
  - [x] Create an img element and set it's src property to equal the nft image link
  - [x] Then append the image to the div with the 'card' class
  - [x] Set the p element with the parent div 'card-text''s textContent property equal to the name of the nft 
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
