### ISSUE TITLE
User can like, dislike or super-like an NFT

### ISSUE THREAD

**Issue by anthony-urbina** [AnthonyUrbina/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The user will now be able to like dislike or super-like the NFT they are currently viewing

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When a user is shown an NFT, they will now be able to interact with it by liking it, disliking it, or super-liking it

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="376" alt="Screen Shot 2022-09-27 at 4 34 20 PM" src="https://user-images.githubusercontent.com/109625982/192655690-a6fdd745-28c8-4c9b-b799-8b6dd34b63f8.png">
<img width="574" alt="Screen Shot 2022-09-27 at 4 34 40 PM" src="https://user-images.githubusercontent.com/109625982/192655708-610b36c4-d3a4-4f8d-867b-31ba16cd1383.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a button to the HTML with a class of like
- [x] Add a button to the HTML with a class of dislike
- [x] Add a button to the HTML with a class of super-like
- [x]  Style and add icons to all 3 buttons
- [x] Create a data model object
  - [x] it should have a NFTvisible property that stores the data (name and image) of the current nft on the swiping page
  - [x] it should have a ratingsInfo property with an array of objects storing the amount of likes and superlikes that collection has received as well as info about that collection (name & image)
  - [x] it should have a superliked property with an array that holds info (name and image) of the individual pieces that were liked
- [x] When the like/superlike/dislike button is clicked (addeventlistener)
  - [x]  it should fetch the name and imageURL of the nft collection that the individual nft being displayed belongs to
    - [x] then store it in an object container
    - [x] add a likes property to the container and set to null
    - [x] then push it to the object within the ratingsInfo property if the object is empty
    - [x] else it should check if an object with a collectionName property that matches the collectionName of the currently visible nft already exists
      - [x] only if a match is not found should you push the newly created object to the ratingsInfo array
      - [x] else you just want update the likes or super likes property of the property according to which button was pressed
      - [x] if liked, it should increment the likes property of the nft collection stored within the data model by 1  
      - [x] If superliked, it should push the individual nft that is curently visible into the superLiked array
       - [x] If the dislike button is clicked it should add 1 to the dislike property of the new object
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
