### ISSUE TITLE
User will be shown a new NFT after their like/dislike

### ISSUE THREAD

**Issue by anthony-urbina** [AnthonyUrbina/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The user will now be able to judge multiple NFT's in a browsing session rather than only one.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After the user performs an action on NFT (like, dislike, super-like) a new image for them to judge will appear on the page.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="375" alt="Screen Shot 2022-09-28 at 3 32 14 PM" src="https://user-images.githubusercontent.com/109625982/192900305-7649d8b0-8bc4-4f92-b0e0-2ca2809b3e7f.png">
<img width="575" alt="Screen Shot 2022-09-28 at 3 32 29 PM" src="https://user-images.githubusercontent.com/109625982/192900311-c82666db-d517-4efb-b0d2-5fcd1314056c.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x]  The user will be shown a random nft from the nft after they rate the current nft 
  - [x] store a copy of the nft list in your data model
  - [x] when a rate button is clicked populate a random nft from the copy of the nft list on to the page
    - [x] generate a random number within the range of the length of the copied nft list
    - [x] use that number to determine which index of the copied array will be selected
      - [x] once found:
        - [x] set the main image photo src equal to the. nfts image
        - [x] set the main image title equal to the nfts name
  - [x] make sure that once it has populated, that it is removed from the cloned list in your data model.
  - [x] the user should be able to rate new nfts until they reach the end of the cloned list
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
