### ISSUE TITLE
User can view their matched collections(recommendations based on their preferred collections)

### ISSUE THREAD

**Issue by anthony-urbina** [AnthonyUrbina/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create the "It's a Match"  modal
  - [x] give it a class of 'hidden'
  - [x] give it a class of 'match-box'
- [x]  Add the message icon to the home page
- [x] Add the mini message icon to the home page 
  - [x] give it a class of hidden
- [x] Show "It's a Match" modal when rate buttons IS clicked and nftList array is empty
  - [x] It's contents will be filled with the nft collection in the data.nftInfo object that has the most likes
- [x] When the user clicks "View All Matches"
  - [x] It should hide the modal
  - [x] You should create a $ul and append it to the page
  - [x] it should call a function that generates a card box for all collections who have a like property value of greater than 0
  - [x] the generateDOMTree function should be creating it's element's with data passed in from the nftInfo object of the collection that the card is being created for
  - [x] once the DOM tree is created, it's return should be appended to the $ul
- [x] When the user clicks Continue "Playing"
  - [x] It should hide the modal
  - [x] it should restart the game but with a different wallet's collection
    - [x] create a property array in the data model to store wallet addresses
    - [x] create a function that loops through and returns one of the wallet addresses in the data model
      - [x] pass it's return to the showFirstNFT() function 
        - [x] it should only make the GET request AFTER a random wallet address has been chosen from the array
          - [x] once the data. has been gathered, remove the wallet that was selected from the data model
- [x] Unhide the mini message icon when a collection in nftInfo object has a like property value of greater than 0
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
