### ISSUE TITLE
Users can see lists of all super-liked NFT’s

### ISSUE THREAD

**Issue by anthony-urbina** [AnthonyUrbina/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a list of all super-liked NFTs.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to navigate to the superlikes view (via the nav bar) and be able to see a list of all super-liked NFT's from that swiping round

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="375" alt="Screen Shot 2022-10-04 at 4 40 18 PM" src="https://user-images.githubusercontent.com/109625982/193950430-2db34868-bfd8-4d4f-acb0-feba68a757b9.png">
<img width="576" alt="Screen Shot 2022-10-04 at 5 56 49 PM" src="https://user-images.githubusercontent.com/109625982/193956757-75e490ce-65f6-41ef-acb2-2281fbe52aef.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a crown icon to the top left of the swipe view
  - [x] it should redirect you to the superlikes view
- [x] The superlikes header should have a back arrow on the left side and a message icon box on the right
  - [x] the back arrow should redirect user to the swipe view
  - [x] the message icon should redirect the user to the matches modal
  - [x] the red mini message icon should appear when the matches view is not empty
- [x] Create a superlikes view
  - [x] add a ul to the HTML
- [x] A new li should be created and appended to the ul when the user clicks the super-like button
  - [x] the li should be created with the data of the nft that was superliked
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
